(() => {
  const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
  const CFG=window.DUCK_CONFIG||{}; const $=s=>document.querySelector(s); const api=async(path,opt={})=>{if(!CFG.apiBase||CFG.apiBase.includes('REPLACE-')) throw Error('API not configured');const headers={'Content-Type':'application/json',...(opt.headers||{})};if(tg?.initData)headers.Authorization=`tma ${tg.initData}`;const r=await fetch(CFG.apiBase.replace(/\/$/,'')+path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'API error');return d};
  const state={tab:'home',services:[],market:[],orders:[],settings:{},user:tg?.initDataUnsafe?.user||{first_name:'دوست عزیز'},wallet:{balance:0,cashback_balance:0}};
  const money=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0)); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('toast-show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('toast-show'),1800)};
  const open=(html)=>{$('#modal').innerHTML=`<div class="modal-bg" id="mb"><section class="sheet">${html}</section></div>`;$('[data-close]')?.addEventListener('click',close);}; const close=()=>$('#modal').innerHTML='';
  async function load(){try{const d=await api('/api/bootstrap');Object.assign(state,{services:d.services||[],market:d.market||[],orders:d.orders||[],settings:d.settings||{},user:d.user||state.user,wallet:d.walletBalance||{}})}catch(e){state.services=demoServices;state.market=demoMarket;state.orders=[];state.settings={hero_text:'همه‌چیز برای تلگرام، یک‌جا و تمیز.'}}render();}
  const demoServices=[{id:'boost',title:'Telegram Boost',description:'بوست کانال با تحویل سریع',icon:'↗',price:150000,unit:'تومان',min_qty:1,max_qty:100,eta_minutes:30,featured:1},{id:'premium',title:'Telegram Premium',description:'اشتراک پرمیوم با شرایط شفاف',icon:'✦',price:980000,unit:'تومان',min_qty:1,max_qty:1,eta_minutes:15},{id:'stars',title:'Telegram Stars',description:'خدمات مبتنی بر Stars',icon:'★',price:100000,unit:'تومان',min_qty:50,max_qty:5000,eta_minutes:10},{id:'gift-rent',title:'Gift Rent',description:'اجاره گیفت‌های خاص',icon:'◇',price:250000,unit:'تومان',min_qty:1,max_qty:30,eta_minutes:60}];
  const demoMarket=[{id:'d1',name:'Ice Cream',number:101,price:1250,discount:20,rarity:'Rare'},{id:'d2',name:'Snoop Dogg',number:210,price:2400,discount:15,rarity:'Legendary'},{id:'d3',name:'Liberty Figure',number:331,price:1890,discount:10,rarity:'Epic'}];
  function render(){document.querySelectorAll('.dock button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));$('#profileChip').textContent=(state.user.first_name||'D').slice(0,1).toUpperCase();const pages={home:home,services:services,market:market,orders:orders,account:account};$('#app').innerHTML=pages[state.tab]();bind();}
  function home(){const featured=state.services.filter(x=>x.featured).concat(state.services).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,4);return `<section class="hero"><div class="eyebrow">DUCK STORE / NEW EXPERIENCE</div><h1>${esc(state.settings.hero_text||'همه‌چیز برای تلگرام، یک‌جا و تمیز.')}</h1><p>کاتالوگ مستقل، Checkout مرحله‌ای و پیگیری سفارش؛ بدون شلوغی اضافه.</p><div class="hero-actions"><button class="btn primary" data-tab="services">شروع خرید</button><button class="btn" data-tab="market">Gift Market</button></div></section><div class="section"><div class="section-head"><h2>دسترسی سریع</h2><span>${state.services.length} خدمت</span></div><div class="quick-grid">${featured.map(s=>`<button class="quick" data-service="${esc(s.id)}"><div class="q-icon">${esc(s.icon)}</div><strong>${esc(s.title)}</strong><small>${esc(s.description)}</small></button>`).join('')}</div></div><div class="section"><div class="section-head"><h2>سه اصل Duck Store</h2><span>UX first</span></div><div class="service-list"><article class="service-card"><div class="service-main"><div class="service-icon">01</div><div><h3>محصول و سفارش جدا</h3><p>کاتالوگ جای سفارش نیست؛ سفارش‌ها فقط تاریخچه خرید تو هستند.</p></div></div></article><article class="service-card"><div class="service-main"><div class="service-icon">02</div><div><h3>قیمت و شرایط شفاف</h3><p>قبل از پرداخت، مقدار، هزینه، تخفیف و ETA را می‌بینی.</p></div></div></article><article class="service-card"><div class="service-main"><div class="service-icon">03</div><div><h3>پیگیری از یک صفحه</h3><p>هر سفارش Timeline خودش را دارد و وضعیت‌ها گم نمی‌شوند.</p></div></div></article></div></div>`}
  function services(){return `<div class="section-head"><h2>خدمات</h2><span>انتخاب کن</span></div><div class="chips">${['همه','boost','premium','stars','gift','channel'].map(x=>`<button class="chip ${x==='همه'?'active':''}">${x==='همه'?'همه':x}</button>`).join('')}</div><div class="service-list">${state.services.map(s=>`<article class="service-card" data-service="${esc(s.id)}"><div class="service-main"><div class="service-icon">${esc(s.icon)}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p><div class="muted">از ${money(s.price)} ${esc(s.unit)} • ${s.eta_minutes?s.eta_minutes+' دقیقه':''}</div></div></div><div class="arrow">‹</div></article>`).join('')}</div>`}
  function market(){return `<div class="section-head"><h2>Gift Market</h2><span>${state.market.length} آیتم</span></div><div class="search"><input id="mq" placeholder="اسم یا شماره گیفت..."><button>⌕</button></div><div class="market-grid" id="marketGrid">${state.market.map(m=>marketCard(m)).join('')}</div>`}
  function marketCard(m){return `<article class="market-card"><div class="market-art">✦</div><div class="market-body"><div class="market-title">${esc(m.name)} #${esc(m.number)}</div><div class="market-sub">${esc(m.rarity||'Collectible')}</div><div class="price-row"><span class="price">${money(m.price)} ⭐</span><span class="discount">-${money(m.discount)}%</span></div><button class="btn primary" style="width:100%;margin-top:10px" data-market="${esc(m.id)}">جزئیات</button></div></article>`}
  function orders(){return `<div class="section-head"><h2>سفارش‌های من</h2><span>${state.orders.length} سفارش</span></div>${state.orders.length?`<div class="service-list">${state.orders.map(o=>`<article class="order-card"><div class="order-row"><div><div class="order-title">${esc(o.title)}</div><div class="order-id">#${esc(o.id)}</div></div><span class="status ${o.status==='completed'?'done':o.status==='cancelled'?'cancelled':''}">${labelStatus(o.status)}</span></div><div class="meta-row"><span>${new Date(o.created_at).toLocaleString('fa-IR')}</span><b>${money(o.total)} ${esc(o.currency==='XTR'?'⭐':'تومان')}</b></div><button class="btn" style="margin-top:10px;width:100%" data-order="${esc(o.id)}">جزئیات و Timeline</button></article>`).join('')}</div>`:`<div class="empty">هنوز سفارشی ثبت نکردی.<br><button class="btn primary" style="margin-top:12px" data-tab="services">دیدن خدمات</button></div>`}`}
  const labelStatus=s=>({pending:'در انتظار',processing:'در حال انجام',completed:'تکمیل‌شده',cancelled:'لغوشده'})[s]||s;
  function account(){return `<article class="account-card"><div class="account-head"><div class="avatar">${esc((state.user.first_name||'D').slice(0,1))}</div><div><strong>${esc([state.user.first_name,state.user.last_name].filter(Boolean).join(' ')||'Telegram User')}</strong><span>${state.user.username?'@'+esc(state.user.username):'Telegram account'}</span></div></div><div class="stats-grid" style="margin-top:15px"><div class="stat-card" style="padding:14px;border-radius:17px"><div class="muted">موجودی</div><strong>${money(state.wallet.balance)} تومان</strong></div><div class="stat-card" style="padding:14px;border-radius:17px"><div class="muted">Cashback</div><strong>${money(state.wallet.cashback_balance)} تومان</strong></div></div><div class="account-actions"><button data-open="wallet">کیف پول <span>›</span></button><button data-open="tickets">پشتیبانی <span>›</span></button><button data-open="referral">دعوت دوستان <span>›</span></button><button data-action="support">ارتباط با علی <span>›</span></button><button data-action="channel">کانال Duck Store <span>›</span></button></div></article>`}
  function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>serviceDetail(b.dataset.service));document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>marketDetail(b.dataset.market));document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>orderDetail(b.dataset.order));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='support')location.href=CFG.supportUrl;if(b.dataset.action==='channel')location.href=CFG.channelUrl});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openSimple(b.dataset.open));$('#mq')?.addEventListener('input',e=>{$('#marketGrid').innerHTML=state.market.filter(m=>`${m.name} ${m.number}`.toLowerCase().includes(e.target.value.toLowerCase())).map(m=>marketCard(m)).join('');document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>marketDetail(b.dataset.market));});}
  function serviceDetail(id){const s=state.services.find(x=>x.id===id);if(!s)return;let fields=[];try{fields=JSON.parse(s.fields_schema||'[]')}catch{};open(`<div class="sheet-head"><div><div class="eyebrow">SERVICE</div><h3>${esc(s.title)}</h3></div><button class="close" data-close>×</button></div><p class="muted">${esc(s.description)}</p><div class="summary"><div><span>قیمت پایه</span><b>${money(s.price)} ${esc(s.unit)}</b></div><div><span>حداقل</span><b>${money(s.min_qty)}</b></div><div><span>حداکثر</span><b>${money(s.max_qty)}</b></div><div><span>تحویل</span><b>${s.eta_minutes?s.eta_minutes+' دقیقه':'—'}</b></div></div><div class="form"><div class="field"><label>تعداد</label><input id="qty" type="number" min="${s.min_qty}" max="${s.max_qty}" value="${s.min_qty}"></div>${fields.map(f=>`<div class="field"><label>${esc(f.label)}${f.required?' *':''}</label>${f.type==='textarea'?`<textarea id="f_${esc(f.key)}" rows="4"></textarea>`:f.type==='select'?`<select id="f_${esc(f.key)}">${(f.options||[]).map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:`<input id="f_${esc(f.key)}" type="${f.type==='number'?'number':'text'}">`}</div>`).join('')}<div class="field"><label>کد تخفیف</label><input id="coupon" placeholder="اختیاری"></div><button class="btn primary" id="createOrder">ادامه سفارش</button></div>`);$('#createOrder').onclick=async()=>{try{const qty=Number($('#qty').value||1), payload={service_id:s.id,qty,coupon:$('#coupon').value,fields:Object.fromEntries(fields.map(f=>[f.key,$('#f_'+f.key)?.value||'']))};const r=await api('/api/orders',{method:'POST',body:JSON.stringify(payload)});close();toast(`سفارش #${r.id} ثبت شد`);await load();state.tab='orders';render()}catch(e){toast(e.message)}}}
  function marketDetail(id){const m=state.market.find(x=>x.id===id);if(!m)return;open(`<div class="sheet-head"><div><div class="eyebrow">GIFT MARKET</div><h3>${esc(m.name)} #${esc(m.number)}</h3></div><button class="close" data-close>×</button></div><div class="market-art" style="border-radius:18px;margin-top:14px">✦</div><div class="summary"><div><span>کمیابی</span><b>${esc(m.rarity||'—')}</b></div><div><span>قیمت</span><b>${money(m.price)} ⭐</b></div><div><span>تخفیف</span><b>${money(m.discount)}%</b></div></div><div class="row-actions"><button class="btn primary" style="flex:1" data-buy-market="${esc(m.id)}">ثبت سفارش</button>${m.telegram_url?`<button class="btn" onclick="location.href='${esc(m.telegram_url)}'">مشاهده در تلگرام</button>`:''}</div>`);$('[data-buy-market]')?.addEventListener('click',async()=>{try{const r=await api('/api/orders',{method:'POST',body:JSON.stringify({market_item_id:m.id,qty:1,payment_method:'stars'})});close();toast(`سفارش #${r.id} ساخته شد`);await load();state.tab='orders';render()}catch(e){toast(e.message)}})}
  async function orderDetail(id){try{const d=await api('/api/orders/'+encodeURIComponent(id));open(`<div class="sheet-head"><div><div class="eyebrow">ORDER TRACKING</div><h3>#${esc(d.order.id)}</h3></div><button class="close" data-close>×</button></div><div class="summary"><div><span>خدمت</span><b>${esc(d.order.title)}</b></div><div><span>مبلغ</span><b>${money(d.order.total)} ${esc(d.order.currency==='XTR'?'⭐':'تومان')}</b></div><div><span>وضعیت</span><b>${labelStatus(d.order.status)}</b></div></div><div class="service-list" style="margin-top:15px">${d.events.map(e=>`<article class="ticket-card"><strong style="font-size:10px">${esc(e.event_type)}</strong><div class="muted">${esc(e.message)}</div><div class="muted">${new Date(e.created_at).toLocaleString('fa-IR')}</div></article>`).join('')}</div>`)}catch(e){toast(e.message)}}
  function openSimple(type){
    if(type==='wallet'){
      return open(`<div class="sheet-head"><h3>کیف پول</h3><button class="close" data-close>×</button></div><div class="summary"><div><span>موجودی</span><b>${money(state.wallet.balance)} تومان</b></div><div><span>Cashback</span><b>${money(state.wallet.cashback_balance)} تومان</b></div></div><p class="muted">شارژ و تسویه کیف پول می‌تواند به Provider پرداخت یا سیستم داخلی متصل شود.</p>`);
    }
    if(type==='referral'){
      return open(`<div class="sheet-head"><h3>Referral</h3><button class="close" data-close>×</button></div><p class="muted">لینک دعوت مخصوص تو بعد از تنظیم Bot start parameter در اینجا ساخته می‌شود.</p><div class="card" style="padding:14px;border-radius:16px">https://t.me/${esc(CFG.storeBotUsername||'YOUR_BOT')}?startapp=REF_${esc(state.user.id||'')}</div>`);
    }
    if(type==='tickets'){
      open(`<div class="sheet-head"><h3>پشتیبانی</h3><button class="close" data-close>×</button></div><div class="form"><div class="field"><label>موضوع</label><input id="ts" value="درخواست پشتیبانی"></div><div class="field"><label>پیام</label><textarea id="tm" rows="5"></textarea></div><button class="btn primary" id="sendTicket">ارسال تیکت</button></div>`);
      $('#sendTicket')?.addEventListener('click',async()=>{
        try{await api('/api/tickets',{method:'POST',body:JSON.stringify({subject:$('#ts').value,message:$('#tm').value})});close();toast('تیکت ثبت شد')}
        catch(e){toast(e.message)}
      });
    }
  }

  load();
})();
