name = "duck-store-api"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "duck-store"
database_id = "3ec662ab-7845-4a31-a117-9aa7c984b097"

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
ADMIN_SESSION_TTL_SECONDS = "43200"
